### ISSUE TITLE
Websocket endpoint

### ISSUE THREAD

**Issue by gokberkkocak** [gokberkkocak/lofigirl#393]
We can add a stateful websocket endpoint to the webserver to use instead of the token based communication. This two way communication will allow event updates on track changes and also can reduce unnecessary /track hits.

- [x] figure out the communication api in websockets i.e. when to send messages between actors #396 
- [x] implementation on server side: `actix-web` supports websockets with `actix-ws` #396
- [x] implementation rust client side: `reqwest-websockets`  #396
- [x] websockets and by its extension the event based implementation brings channel based communication. we can extend this functionality to standalone client.  #396
