### ISSUE TITLE
Deprecate original track endpoints

### ISSUE THREAD

**Issue by gokberkkocak** [gokberkkocak/lofigirl#397]
With the new dynamic track endpoint /track/{url}  and event based websocket endpoint `/track_ws` we can retire the original `/track/1` and `/track/2`.

To do this, we will need to migrate wasm and flutter frontends to one of the new communication methods.

- [x] Migrate web wasm frontend to dynamic rest or websocket endpoint. #405 
- [x] Migrate flutter frontend to dynamic rest or websocket endpoint. #408 
- [x] Remove `/track/1` and `/track/2` from the server and docs. Also remove server video settings from configuration. #409
